name: Build and upload to PyPI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - trotta/win-test
#  release:
#    types:
#      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          #- {os: ubuntu-latest, arch: x86_64, build: 'cp*-manylinux*'}
          #- {os: ubuntu-24.04-arm, arch: aarch64, build: 'cp*-manylinux*'}
          - {os: windows-latest, arch: AMD64, build: 'cp*'}
          #- {os: macos-14, arch: arm64, build: 'cp*'}
          #- {os: macos-13, arch: x86_64, build: 'cp*',}

    steps:
      - uses: astral-sh/setup-uv@v4

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS_MACOS: ${{ matrix.arch }}
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_ARCHS_WINDOWS: ${{ matrix.arch }}
          CIBW_BUILD: ${{ matrix.build }}
          CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ matrix.arch }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

