name: Build Docs

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy_docs:
    name: Deploy Docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.7.13"
          python-version: "3.12"
          activate-environment: true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"

      - name: Installing dependencies
        run: |
          uv pip install nanobind -r docs/requirements.txt
          gem install jekyll jekyll-remote-theme

      - name: Build the local package
        run: |
          cmake -B build -G Ninja
          cmake --build build

      - name: Build the docs
        run: |
          ./scripts/build_site.sh

      - name: Deploying on GitHub Pages
        if: github.ref == 'refs/heads/main' && github.repository_owner == 'mlc-ai'
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.MLC_GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git config --global user.email "mlc-gh-actions-bot@nomail"
          git config --global user.name "mlc-gh-actions-bot"
          ./scripts/gh_deploy_site.sh
